/* NavAuiShim */
(function(x){x.execute(function(){(function(e){document.createElement("header");var a=function(b){function d(a,b,d){a[d]=function(){c._replay.push(b.concat({m:d,a:[].slice.call(arguments)}))}}var c={};c._sourceName=b;c._replay=[];c.getNow=function(a,b){return b};c.when=function(){var a=[{m:"when",a:[].slice.call(arguments)}],b={};d(b,a,"run");d(b,a,"declare");d(b,a,"publish");d(b,a,"build");return b};d(c,[],"declare");d(c,[],"build");d(c,[],"publish");d(c,[],"importEvent");a._shims.push(c);return c};
a._shims=[];if(!e.$Nav)e.$Nav=a("rcx-nav");if(!e.$Nav.make)e.$Nav.make=a})(window)})})(function(){var x=window.AmazonUIPageJS||P,e=x.attributeErrors;return e?e("NavAuiShim"):x}());
;/* RetailSearchAutocompleteAssets */
(function(C){C.execute(function(){window.$Nav.when("$","nav.inline").run(function(d){window.$Nav.declare("config.blackbelt",d("#nav-belt").length>0)});window.$Nav.when("config.blackbelt").run(function(d){d?window.$Nav.when("searchApi").run(function(c){window.$Nav.declare("sxSearchApi",c)}):window.$Nav.declare("sxSearchApi")});window.$Nav.when("$","sxSearchApi","sx.iss.DomUtils").build("NavDomApi",function(d,c,b){var g,a,e;function i(){return l?j().find('input[type="text"]'):(typeof k==="undefined"&&
(k=d(g)),k)}function h(){return l?c.flyout.elem():(typeof s==="undefined"&&(s=d(r),j().after(s)),s)}function f(){return l?c.options().parents("select"):(typeof u==="undefined"&&(u=d(a)),u)}function j(){return l?c.options().parents("form"):d(e)}function n(){var a=o(),b=h();h().is(":visible")&&!(b.html().length<1)&&b.css({left:a.offset().left,width:a.width()})}function o(){p===void 0&&(p=d("#nav-iss-attach"));return p}var l=c!==void 0;g="#twotabsearchtextbox";a="#searchDropdownBox";e="#nav-searchbar";
var k,m,s,u,p,r='<div id="search-dropdown" class="search-dropdown"></div>',q=/search-alias\s*=\s*([\w-]+)/;c===void 0&&d(window).resize(n);return{getAliasDropdown:f,getSearchBox:i,getSearchBoxId:function(){return g},getSearcchSuggestions:function(){typeof m==="undefined"&&(m=d("#srch_sggst"));return m},getKeyword:function(){var a;a=c!==void 0?c:i();return b.getKeyword(a)},setKeyword:function(a){if(c!==void 0)c.val(a);else return i().val(a)},getAliasFromDropdown:function(){var a=f().val();return(a=
a&&a.match(q))?a[1]:void 0},getCategoryNameFromDropdown:function(a){var b="";a?(a=f().find('option[value$="search-alias='+a+'"]'),b=a.length>0?d(a[0]).text():b):b=f().find("option:selected").text();return d.trim(b)},getDropdown:h,showDropdown:function(a){l?(typeof a!=="undefined"&&c.flyout.elem().html(a),c.flyout.show()):(typeof a!=="undefined"&&h().hide().html(a),a=o(),h().css({left:a.offset().left,width:a.width()}).show())},hideDropdown:function(){l?c.flyout.hide():h().hide()},getOption:function(a){if(!a)return f().find("option:selected");
a=f().find('option[value$="search-alias='+a+'"]');return a.length>0?d(a[0]):d()},getForm:j,getIssPrefixElem:function(){return d("#issprefix")},getSuggestions:function(){return d(".s-suggestion")},submitForm:function(){j().submit()},getOriginalSearchTerm:function(){return j().data("originalSearchTerm")},getOriginalAlias:function(){return j().data("originalAlias")},isSearchBoxFocused:function(){return i().get(0)===document.activeElement},activateSearchBox:function(){j().addClass("nav-active")},deactivateSearchBox:function(){j().removeClass("nav-active")},
getSearchApi:function(){return c}}});window.$Nav.build("sx.iss.TemplateEngine",function(){var d={};return function b(g,a){var e=/^[a-zA-Z0-9_-]+$/.test(g)?d[g]=d[g]||b(document.getElementById(g).innerHTML):new Function("obj","var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push('"+g.replace(/[\r\t\n]/g," ").replace(/'(?=[^#]*#>)/g,"\t").split("'").join("\\'").split("\t").join("'").replace(/<#=(.+?)#>/g,"',$1,'").split("<#").join("');").split("#>").join("p.push('")+"');}return p.join('');");
return a?e(a):e}});window.$Nav.when("$").build("sx.iss.TemplateInstaller",function(d){function c(b,c){var a=document.createElement("script");a.setAttribute("type","text/html");a.setAttribute("id",b);a.text=c;return a}d("body");return{init:function(){var b=document.createDocumentFragment();b.appendChild(c("s-suggestion",'<div id="<#= suggestionId #>"class="s-suggestion"data-alias="<#= alias #>"data-keyword="<#= keyword #>"data-store="<#= store #>"data-isSc="<#= isSpellCorrected #>"data-isFb="<#= isFallback #>"data-type="<#= type #>"><#= bprefix #><span class="s-heavy"><#= prefix #></span><#= suffix #><# if (typeof storeHtml === "string") { #> <#= storeHtml #><# } #></div>'));
b.appendChild(c("suggestions-template",'<div id="suggestions-template"><# if (typeof suggestionTitle !== "undefined") { #><div id="suggestion-title"><#= suggestionTitle #></div><# } #><div id="suggestions"><# if (typeof suggestions !== "undefined") {for(var i=0; i < suggestions.length; i++) {var displayString = suggestions[i].display; #><#= displayString #><# }} #></div></div>'));b.appendChild(c("s-separator",'<div id="s-separator"><div class="s-separator"></div></div>'));b.appendChild(c("s-department",
'<div id="<#= suggestionId #>" class="s-suggestion s-highlight-primary"data-alias="<#= alias #>"data-keyword="<#= keyword #>"data-store="<#= store #>"data-type="<#= type #>">Shop the <#= beforePrefix #><span class="s-heavy"><#= prefix #></span><#= suffix #> store</div>'));b.appendChild(c("s-option",'<option value="<#= value #>"><#= store #></option>'));b.appendChild(c("s-minimal",'<div class="s-suggestion s-custom" data-url="<#= url #>"><#= bprefix #><span class="s-heavy"><#= prefix #></span><#= suffix #></div>'));
b.appendChild(c("s-storeText",'<span class="<#= cssClasses #>"><#= store #></span>'));b.appendChild(c("s-corpus",'<div class="s-suggestion" id="<#= suggestionId #>"data-alias="<#= alias #>"data-url="<#= url #>"data-type="<#= type #>"data-keyword="<#= keyword #>"><#= bprefix #><span class="s-heavy"><#= prefix #></span><#= suffix #></div>'));document.body.appendChild(b)}}});window.$Nav.when("sx.iss.DebugUtils","sx.iss.DomUtils").build("sx.iss.EventBus.instance",function(d,c){return new function(){function b(a){var b=
typeof a,c="";b==="object"&&a.hasOwnProperty("name")?c=a.name:b==="string"&&(c=a);return c}var g={},a={};this.listen=function(a,i,h){var f,j="";if(c.isArray(a)){for(f=0;f<a.length;f++)j=a[f],this.listen(j,i,h),d.logDebug("Listening for: "+j);return this}j=b(a);g[j]||(g[j]=[]);g[j].push({f:i,o:h});d.logDebug("Listening for: "+j);return this};this.trigger=function(a,c){var h=b(a);d.logDebugWithTrace("Trigger: "+h,c);var h=g[h],f;if(h){for(f=0;f<h.length;f++)h[f].f.call(h[f].o,c);return this}};this.triggerThrottledEvent=
function(c,i,h){var f=b(c);d.logDebugWithTrace("Trigger (throttled): "+f,i);var j=g[f],c=a[f];if(j)return h===void 0&&(h=100),c&&(clearTimeout(c),delete a[f]),c=setTimeout(function(){var b;for(b=0;b<j.length;b++)j[b].f.call(j[b].o,i);delete a[f]},h),a[f]=c,this}}});window.$Nav.when("$","sx.iss.utils","sx.iss.Events","NavDomApi","sx.iss.DebugUtils").build("sx.iss.PublicApi",function(d,c,b,g,a){function e(a){g.getSearchBox().focus(a)}function i(a){a===void 0?g.getSearchBox().blur():g.getSearchBox().blur(a)}
var h=/node\s*=\s*([\d]+)/,f=/bbn\s*=\s*([\d]+)/,j=/^me=([0-9A-Z]*)/,n=/^\s+/,o=/\s+/g;return{searchAlias:function(){return g.getAliasFromDropdown()},searchNode:function(){var a=g.getAliasDropdown().val().match(h);return a?a[1]:null},bbn:function(){var a=g.getAliasDropdown().val().match(f);return a?a[1]:null},merchant:function(){var a=g.getAliasDropdown().val().match(j);return a?a[1]:null},encoding:function(){var a=g.getForm().find('input[name^="__mk_"]');if(a.length)return[a.attr("name"),a.val()]},
keyword:function(){return g.getSearchBox().val().replace(n,"").replace(o," ")},submit:function(b){a.logDebugWithTrace("Attaching the submit event handler to the form...");g.getForm().submit(b)},suggest:function(a){c.eventBus.listen(b.globals.suggestionsRendered,function(b){var c=[];d.each(b.suggestions,function(a,b){b.type!=="separator"&&c.push(b)});a(b.searchTerm,c)})},onFocus:e,onBlur:i,focus:e,blur:i,isImeEnhUsed:function(){return!1},keydown:function(a){var b="#"+g.getSearchBox().attr("id");g.getForm().delegate(b,
"keydown",a)}}});window.$Nav.when("$","sx.iss.utils","sx.iss.DebugUtils").build("sx.iss.Weblab",function(d,c,b){return function(d,a){function e(a){d.hasOwnProperty(a)&&(d[a](),b.logDebug("Triggering: "+a+" weblabs"))}c.eventBus.listen(a.keydown,function(){e("doCTWKeydown")});c.eventBus.listen(a.suggestionsRendered,function(){e("doCTWDisplay")})}});window.$Nav.when("$","sx.iss.utils","sx.iss.SuggestionTypes","NavDomApi","sx.iss.ReftagBuilder","sx.iss.DebugUtils").build("sx.iss.Reftag",function(d,c,
b,g,a,e){return function(b,d,f){function j(b){return(new a).build(b,f.hasOwnProperty("shouldAddImeTag")&&f.shouldAddImeTag())}function n(b){if(b.suggestions===void 0||b.searchTerm===void 0)e.logDebug('"suggestions" or "searchTerm" is undefined',b);else{for(var c=a.CONSTANTS.noSearchTermMatchInResults,d=b.searchTerm,b=b.suggestions,f=0;f<b.length;f++)if(d===b[f].keyword){c=a.CONSTANTS.searchTermMatchInResults;break}k(c)}}function o(){k(a.CONSTANTS.noResults)}function l(a){a.suggestion===void 0||a.searchTerm===
void 0?e.logDebug('"suggestion" or "searchTerm" is undefined',a):k(j(a))}function k(b){var c=/(ref=[\-\w]+)/,e=/(dd_[a-z]{3,4})(_|$)[\w]*/,d=g.getForm(),f=d.attr("action");c.test(f)?f=e.test(f)?f.replace(e,"$1_"+b):f.replace(c,a.CONSTANTS.reftagBase+b):(f.charAt(f.length-1)!=="/"&&(f+="/"),f+=b);d.attr("action",f)}d===void 0&&(d={});f===void 0&&(f={});c.eventBus.listen(b.selectionChange,l);c.eventBus.listen(b.suggestionsRendered,n);c.eventBus.listen(b.noSuggestions,o);return{create:j,updateReftagAfterRender:n,
updateReftagAfterSelection:l,updateReftagAfterNoSuggestions:o,updateFormActionWithReftag:k}}});window.$Nav.when("$","sx.iss.utils","sx.iss.SuggestionTypes","sx.iss.DataAttributes","NavDomApi","sx.iss.DebugUtils").build("sx.iss.ReftagBuilder",function(d,c,b,g,a,e){function i(){function c(a){a!==void 0&&l.push(a);return this}function i(b){var b=a.getOption(b.data("alias")).val(),c=b.indexOf("=");if(c===-1)return"";var b=b.substr(c+1),c=b.indexOf("-"),e=b.substr(0,3);return c?e:e+b.charAt(c+1)}function n(d,
m){var s=d.suggestion,n=d.searchTerm;e.logDebug("Build reftag for search term: "+n,s);a.getSuggestions();var p=o(s),r=p.reftag;c(h.base);m&&c(h.ime);var q;if(s.data(g.fallback.name)===!0)q=h.fallback;else if(s.data(g.spellCorrected.name)===!0)q=h.spellCorrected;q!==void 0?c(q):(s.data("type")===b.department.name&&(c(b.a9Xcat.reftag),c(s.data("alias"))),c(r));r!==b.a9.reftag&&r!==b.a9Corpus.reftag?c(0):(p=p.name,p=a.getDropdown().find('.s-suggestion[data-type="'+p+'"]').index(s)+1,c(p));s===void 0?
(c(h.undefinedSugg),s=i(s),c(s)):c(n.length);return l.join(h.separator)}function o(a){var c=b.a9;d.each(b,function(b,e){if(a.data("type")===e.name)return c=e,!1});return c}function i(a){var a=a.val(),b=a.indexOf("=");if(a!==""||b===-1)return"";var a=a.substr(b+1),b=a.indexOf("-")+1,c=a.substr(0,3);return b?c:c+a.charAt(b)}var l=[];return{build:n,buildFull:function(a,b){return h.reftagBase+n(a,b)}}}var h={base:"ss",fallback:"fb",spellCorrected:"sc",undefinedSugg:"dd",reftagBase:"ref=nb_sb_",noResults:"noss",
searchTermMatchInResults:"noss_1",noSearchTermMatchInResults:"noss_2",ime:"ime",separator:"_"};i.CONSTANTS=h;return i});window.$Nav.when("NavDomApi","sx.iss.DebugUtils").build("sx.iss.suggestionUtils",function(d,c){function b(a){var b;typeof d.getAliasFromDropdown()==="undefined"&&a&&(b=a.searchAliasAccessor());return b}var g=/\s/;return{getPrefixPos:function(a,b){return a.toLowerCase().indexOf(b.toLowerCase())},getPrefixPosMultiWord:function(a,b){var c=a.toLowerCase().indexOf(b.toLowerCase()),d;
if(c===-1)return-1;if(c===0)return 0;d=a[c-1];return d===" "||d==="\t"||d.match(g)?c:-1},splitStringForDisplay:function(a,b,c){return{bprefix:a.substr(0,b),prefix:a.substr(b,c),suffix:a.substr(b+c)}},getDeepNodeAlias:b,getDeepNodeCategoryName:function(a,b){var c;a&&(c=d.getCategoryNameFromDropdown(a)||b.searchAliasDisplayNameAccessor());return c},shouldRequestSuggestions:function(a,e){var g;if((a==="department"||a==="a9")&&e.hasOwnProperty("aliases")){var h=d.getAliasFromDropdown()||b(e.deepNodeISS);
g=e.aliases==="*"||e.aliases.indexOf(h)>-1;c.logDebug("Should we request suggestions for: alias : "+h+" provider : "+a+"? "+g);return g}return!0}}});window.$Nav.when("sx.iss.TimingProvider.instance","sx.iss.EventBus.instance","sx.iss.suggestionUtils","sx.iss.DependenciesMet").build("sx.iss.utils",function(d,c,b){return{timingProvider:d,eventBus:c,suggestionUtils:b,now:function(){return(new Date).getTime()},escapeRegExp:function(b){return b.replace(/([.*+?\^${}()|\[\]\/\\])/g,"\\$1")}}});window.$Nav.when("$").build("sx.iss.DomUtils",
function(){var d=/\+/g,c=/^\s+/;(function(){if(!Array.prototype.indexOf)Array.prototype.indexOf=function(b,c){var a=this.length>>>0,e=Number(c)||0,e=e<0?Math.ceil(e):Math.floor(e);for(e<0&&(e+=a);e<a;e++)if(e in this&&this[e]===b)return e;return-1}})();return{isHoveredClass:"is-hovered",getKeyword:function(b){return(b=b.val())?b.replace(c,""):b},isElHoveredOver:function(b){return b.hasClass("is-hovered")},hoverOverEl:function(b){return b.addClass("is-hovered")},hoverOutEl:function(b){return b.removeClass("is-hovered")},
isArray:function(b){return Object.prototype.toString.call(b)==="[object Array]"},getFormParams:function(b){for(var b=b.split("?"),c=b.length>1?b[1]:void 0,c=c?c.split("&"):[],a=c.length,e;a-- >0;)e=c[a].split("="),c[a]={name:e[0],value:e[1].replace(d," ")};return{uri:b[0],formParams:c}},suggestionClass:".s-suggestion",hiddenInputValue:"frmDynamic",hiddenInputClass:".frmDynamic",areAnySuggestionsHoveredOver:function(b){return b.find(".is-hovered").length>0},getCursorPosition:function(b){b=b.get(0);
if("selectionStart"in b)return b.selectionStart;else if(document.selection){b.focus();var c=document.selection.createRange(),a=c.text.length;c.moveStart("character",-b.value.length);return c.text.length-a}return-1}}});window.$Nav.build("sx.iss.DebugUtils",function(){function d(b){if(b&&b.length>0)for(var b=b.substring(1).split("&"),c=0;c<b.length;c++){var d=b[c].split("=");if(d[0]==="debug"){for(var f in a)a.hasOwnProperty(f)&&(a[f]=d[1].indexOf(f)!==-1?!0:!1);break}}}function c(){return a.iss||a.isstrace}
function b(){return a.isstrace}function g(a,b){c()&&window.console&&(b!==void 0?console.debug(a,b):console.debug(a))}var a={iss:!1,isstrace:!1,noiss:!1,isspolyfill:!1};d(window.location.search);return{init:d,logDebug:g,logDebugWithTrace:function(a,c){g(a,c);b()&&console.trace()},isDebugModeOn:c,isDebugModeOnWithTrace:b,isDisableISS:function(){return a.noiss},isUsingPolyFill:function(){return a.isspolyfill}}});window.$Nav.build("sx.iss.ObjectUtils",function(){return{freeze:function(d){Object.freeze&&
d&&Object.freeze(d)}}});window.$Nav.when("$","sx.iss.DebugUtils").run(function(d,c){c.isDisableISS()||((!d.fn.delegate||c.isUsingPolyFill())&&d.extend(d.fn,{delegate:function(b,g,a){return this.bind(g,function(e){var g=d(e.target);if(g.is(b)||g.parents(b).length>0)return c.logDebug("delegate ",{selector:b,target:g,event:e}),a.apply(g,arguments)})}}),window.$Nav.declare("sx.iss.DependenciesMet"))});window.$Nav.when("sx.iss.DepartmentDataFormatter").build("sx.iss.DepartmentData",function(){return{getData:function(){return[]}}});
window.$Nav.build("sx.iss.DepartmentDataFormatter",function(){return{format:function(d){for(var c=[],b=0;b<d.length;b++){var g=d[b];c.push({id:g[0],alias:g[0],keyword:"",type:"department",store:g[1],name:"",triggerWords:g[2],sn:!1})}return c}}});window.$Nav.when("sx.iss.ObjectUtils").build("sx.iss.SuggestionTypes",function(d){var c={a9:{name:"a9",reftag:"i",templateId:"s-suggestion"},a9Xcat:{name:"a9-xcat",reftag:"c",templateId:"s-suggestion"},a9Corpus:{name:"a9-corpus",reftag:"cp",reftagTemplate:"REF_TAG",
templateId:"s-corpus"},department:{name:"department",reftag:"deptiss",templateId:"s-department"}};d.freeze(c);return c});window.$Nav.build("sx.iss.DataAttributes",function(){return{fallback:{name:"isfb"},spellCorrected:{name:"issc"}}});window.$Nav.build("sx.iss.TimingEvents",function(){return{latency:{group:"Latency",events:{timeToDisplay:"timeToDisplay"}}}});window.$Nav.when("sx.iss.DebugUtils").build("sx.iss.Events",function(d){function c(){var b=Date.now();return{uid:b,suggestionsReadyForDisplay:{name:"suggestionsReadyForDisplay-"+
b},suggestionsReady:{name:"suggestionsReady-"+b},suggestionsRendered:{name:"suggestionsRendered-"+b},updateSearchBox:{name:"updateSearchBox-"+b},selectionChange:{name:"selectionChange-"+b},dropdownHidden:{name:"dropdownHidden-"+b},updateSearchTerm:{name:"updateSearchTerm-"+b},suggestionClicked:{name:"suggestionClicked-"+b},suggestionsNeeded:{name:"suggestionsNeeded-"+b},a9SuggestionsNeeded:{name:"a9-suggestionsNeeded-"+b},noSuggestions:{name:"nosuggestions-"+b},searchBoxFocusIn:{name:"searchBoxFocusIn-"+
b},searchBoxFocusOut:{name:"searchBoxFocusOut-"+b},keydown:{name:"keydown-"+b},hideDropdown:{name:"hidedropdown-"+b}}}return{globals:{issLoaded:{name:"issLoaded"},suggestionsRendered:{name:"suggestionsRendered"},initializeNavSearchBox:{name:"initializeSearchBox"}},createInstance:function(){return new c},createEvent:function(b,c){var a=c;c.hasOwnProperty("name")?a=c.name:typeof c==="string"?a=c:d.logDebug('Format of "event" parameter is not a string or an event object',c);return b+"-"+a}}});window.$Nav.when("sx.iss.ObjectUtils").build("sx.iss.Platform",
function(d){var c={name:"desktop",cid:"amazon-search-ui",callback:"String",needExtraParams:!0};d.freeze(c);return c});window.$Nav.when("$").build("sx.iss.TimingProvider.instance",function(d){return new function(){var c={};this.startTimer=function(b,d){c[b]||(c[b]={});c[b][d]={start:+new Date}};this.stopTimer=function(b,d){var a=c[b]&&c[b][d];if(!a)return-1;a.end=+new Date;return a.end-a.start};this.getTimings=function(b){return c[b]};this.getTimingStats=function(b){var g={name:b},a=0,e=0,i=void 0,
h=void 0,f=0,j=0,n=[],o=0,l=0;if(c[b]){d.each(c[b],function(a,b){if(b.start&&b.end){j=b.end-b.start;n.push(j);f++;e+=j;if(!i||j<i)i=j;if(!h||j>h)h=j}});n.sort();g.n=f;g.avg=e/f;g.min=i;g.max=h;g.med=f===1?n[0]:f%2?(n[Math.floor(f/2)]+n[Math.ceil(f/2)])/2:n[f/2];for(a=0;a<f;a++)o=n[a]-g.avg,o*=o,l+=o;g.stddev=Math.sqrt(l/f);return g}};this.getTimingWithDisplayLatency=function(b,d){var a=c[b]&&c[b][d];return!a?-1:a.end-a.start+100}}});window.$Nav.when("$","sx.iss.utils","NavDomApi","sx.iss.Events",
"sx.iss.DomUtils","sx.iss.SuggestionTypes","sx.iss.A9SuggestionQueryConstructors","sx.iss.A9SuggestionResultsProcessors","sx.iss.DebugUtils").build("sx.iss.A9SuggestionProvider",function(d,c,b,g,a,e,i,h,f){var j="a9",n=e.a9;return function(a,l,k){function m(a,b){var h=++u,i,m;p=document.getElementsByTagName("head").item(0);r="JscriptId"+h;q=document.createElement("script");q.setAttribute("type","text/javascript");q.setAttribute("charset","utf-8");q.setAttribute("src",b);q.setAttribute("id",r);q.onload=
q.onreadystatechange=function(){if(!(i||this.readyState!==void 0&&this.readyState!=="loaded"&&this.readyState!=="complete")){i=!0;if(completion!=="undefined"){var b=s(),l=!b||d.inArray(b,w)===-1?e.a9:e.a9Corpus;m=t.getResultsProcessor(l.name).processResults(a,b,completion)}this.onload=this.onreadystatechange=null;try{p.removeChild(q)}catch(o){f.logDebug(o)}c.timingProvider.stopTimer(j,h);b={searchTerm:a,suggestionSets:m};l=g.createEvent(j,k.suggestionsReady);c.eventBus.trigger(l,b)}};c.timingProvider.startTimer(j,
h);p.appendChild(q)}function s(){var a="aps",a=[],a=l.aliases;(a=l.implicitAlias?[l.implicitAlias]:typeof a==="string"?a.split(","):a)&&a.length===1?a=a[0]:(a=b.getAliasFromDropdown(),typeof a==="undefined"&&(a=c.suggestionUtils.getDeepNodeAlias(l.deepNodeISS)));return a}var u=0,p,r,q,x=new i(l),t=new h(l),w=l.issCorpus||[];c.eventBus.listen(k.a9SuggestionsNeeded,function(a){if(c.suggestionUtils.shouldRequestSuggestions(j,l))if(!a||!a.length){var a={searchTerm:a,suggestions:[]},b=g.createEvent(j,
k.suggestionsReady);c.eventBus.trigger(b,a)}else{var b=s(),f=!b||d.inArray(b,w)===-1?e.a9:e.a9Corpus;(b=x.getUrlConstructor(f.name).constructUrl(a,b))&&m.call(this,a,b)}},this);return{getName:function(){return j},processResults:t.getResultsProcessor(n.name).processResults}}});window.$Nav.when("$","sx.iss.utils","NavDomApi","sx.iss.DomUtils","sx.iss.SuggestionTypes","sx.iss.Platform","sx.iss.DebugUtils").build("sx.iss.A9SuggestionQueryConstructors",function(d,c,b,g,a,e,i){return function(h){function f(a){return{constructUrl:function(){i.logDebugWithTrace("Invalid suggestion type provided: "+
a+" when asking for query constructors");return""}}}function j(){var a=k+"//"+h.src,b={method:"completion",mkt:h.mkt,client:e.cid,x:e.callback};return{constructUrl:function(c,f){var g=d.extend({},b,{"search-alias":f},n(c));e.needExtraParams&&d.extend(g,l());return a+o(g)}}}function n(a){var c=g.getCursorPosition(b.getSearchBox());return c>-1?{q:encodeURIComponent(d.trim(a.substring(0,c))),qs:encodeURIComponent(a.substring(c))}:{q:encodeURIComponent(a)}}function o(a){var b="?";d.each(a,function(a,
c){b+=a+"="+c+"&"});return b}function l(){var a={xcat:h.xcat,cf:h.cf,noCacheIE:c.now()};if(h.fb!==void 0)a.fb=h.fb;if(h.np!==void 0)a.np=h.np;a.sc=1;return a}var k=h.protocol||window.parent.document.location.protocol||"http:";k==="file:"&&(k="http:");var m={};m[a.a9.name]=new j;m[a.a9Xcat.name]=new j;m[a.a9Corpus.name]=new function(){var a=k+"//"+h.src.replace("search","v2.0"),b={"num-corpus":5,"num-query":0,client:e.cid,mkt:"ATVPDKIKX0DER",fb:1,xcat:0,method:"completion",cf:0,sc:1,conf:1,x:e.callback};
return{constructUrl:function(c,e){var f=d.extend({},b,{"search-alias":e},n(c));return a+o(f)}}};return{getUrlConstructor:function(a){return m.hasOwnProperty(a)?m[a]:new f(a)}}}});window.$Nav.when("$","sx.iss.utils","NavDomApi","sx.iss.DomUtils","sx.iss.SuggestionTypes","sx.iss.DebugUtils").build("sx.iss.A9SuggestionResultsProcessors",function(d,c,b,g,a,e){return function(d){function g(a){return{processResults:function(){e.logDebugWithTrace("Invalid suggestion type provided: "+a+" when asking for result processing");
return""}}}var f={};f[a.a9.name]=new function(){function e(a,c){var f={type:a.type,bprefix:a.bprefix,prefix:a.prefix,suffix:a.suffix,keyword:a.keyword,alias:a.alias||c,isSpellCorrected:a.isSpellCorrected,isFallback:a.isFallback,isDeepNode:a.isDeepNode},g;if(f.type==="a9-xcat"||f.isDeepNode===!0){if(a.isFirst||!d.noXcats)a.store?g=a.store:a.isFirst&&(g=b.getCategoryNameFromDropdown())}else g=void 0;f.store=g;g=f.alias;var h="/s?k="+encodeURIComponent(a.keyword);typeof g!==void 0&&(h+="&i="+encodeURIComponent(g));
f.url=h;return f}var f=a.a9.name;return{processResults:function(g,h,k){var m=k[1],s=k.length>2?k[2]:[],u=0,k=[],p=[],r,q,x;x=!1;for(var t=0;t<s.length;t++){var w=s[t];if(w.hasOwnProperty("source"))for(var w=w.source,v=0;v<w.length;v++)if(w[v]==="fb"){x=!0;break}}t=!1;for(w=0;w<s.length;w++)if(v=s[w],v.hasOwnProperty("nodes")&&v.nodes.length>0){t=!0;break}d.deepNodeISS&&(r=c.suggestionUtils.getDeepNodeAlias(d.deepNodeISS),q=c.suggestionUtils.getDeepNodeCategoryName(r,d.deepNodeISS));for(w=0;w<m.length;w++){var v=
r,z=q,A=g,y=m[w],E=w,D=s&&s[E]&&s[E].sc==="1",C=c.suggestionUtils.getPrefixPos(y,A),F=void 0,G=void 0,B=void 0,B=void 0;D||C===-1?(F=y,G=B=""):(B=c.suggestionUtils.splitStringForDisplay(y,C,A.length),F=B.bprefix,G=B.prefix,B=B.suffix);v={type:f,isSpellCorrected:D,bprefix:F,prefix:G,suffix:B,keyword:y,isFirst:E===0,alias:v,store:z,isDeepNode:v!==void 0&&z!==void 0};if(!x)if(A=k,z=v,y=h,w===0&&typeof r==="undefined"&&t){A=p;z.isFirst=!1;z.type="a9-xcat";y=b.getAliasFromDropdown();if(y!=="aps")z.store=
b.getCategoryNameFromDropdown(y),z.alias=y,A.push(e(z,void 0));z.store=b.getCategoryNameFromDropdown("aps");z.alias="aps";A.push(e(z))}else A.push(e(z,y));if(!d.noXcats){z=s[w];A=z.nodes||[];for(y=0;y<A.length&&u<4;y++)E=A[y],D=z,v.store=E.name,v.alias=E.alias,v.type="a9-xcat",v.isFallback=D&&D.source&&D.source[0]==="fb",p.push(e(v,h)),u++}}g={};g[a.a9.name]=k;g[a.a9Xcat.name]=p;return g}}};f[a.a9Corpus.name]=new function(){var b=a.a9Corpus;return{processResults:function(e,d,f){var g=[],f=f.suggs;
if(f.length===0)return g;for(var h=0;h<f.length;h++){var i=f[h];if(!(i.hasOwnProperty("conf")&&i.conf<80)){var u=i.corpus,p;p=i.source;for(var r=[],q=0;q<p.length;q++)r.push(p[q].field);p=r;for(r=0;r<u.length&&g.length<5;r++){var q=u[r],x;x=i;for(var t=q.asin_info,w=p,v="",z=0;z<t.length;z++){var A=t[z],y=A.type,A=A.value;y==="title"&&(v+=A[0]);w.indexOf(y)>=0&&A.indexOf(x.sugg)>=0&&(y==="actor"?v+=", starring "+x.sugg:y==="director"&&(v+=", directed by "+x.sugg))}x=v;t=c.suggestionUtils.getPrefixPos(x,
e);t===-1?(t=x,w=v=""):(v=c.suggestionUtils.splitStringForDisplay(x,t,e.length),t=v.bprefix,w=e,v=v.suffix);g.push({text:x,url:"/dp/"+q.asin+"/"+a.a9Corpus.reftagTemplate+"?keywords="+e,type:b.name,keyword:e,alias:d,bprefix:t,prefix:w,suffix:v})}}}e={};e[a.a9Corpus.name]=g;return e}}};return{getResultsProcessor:function(a){return f.hasOwnProperty(a)?f[a]:new g(a)}}}});window.$Nav.when("$","sx.iss.utils","sx.iss.DepartmentData","NavDomApi","sx.iss.Events").build("sx.iss.DepartmentSuggestionProvider",
function(d,c,b,g,a){function e(e,n){function o(l){if(c.suggestionUtils.shouldRequestSuggestions(i,e)){var k={searchTerm:l,suggestionSets:{}},m=[],o=RegExp("\\b"+c.escapeRegExp(l)+"(.*)","i");if(l.length>=h&&g.getKeyword().length===l.length){var u,p,r,q;d.each(b.getData(e),function(a,b){q=r=p="";if(o.test(b.triggerWords)||o.test(b.store)){b.position=m.length===0?0:m.length+1;var e=c.suggestionUtils.getPrefixPos(b.store,l);e===-1?q=b.store:(u=c.suggestionUtils.splitStringForDisplay(b.store,e,l.length),
p=u.bprefix,r=u.prefix,q=u.suffix);b.beforePrefix=p;b.prefix=r;b.suffix=q;m.push(b);if((e=window.ue)&&e.count){var d=i+b.alias.replace("-","");e.count(d,e.count(d)+1)}}if(m.length===f)return!1})}k.suggestionSets[i]=m;var x=a.createEvent(i,n.suggestionsReady);c.eventBus.trigger(x,k)}}(function(){var b=a.createEvent(i,n.suggestionsNeeded);c.eventBus.listen(b,o)})()}var i="department",h=3,f=3;e.prototype.getName=function(){return i};return e});window.$Nav.when("sx.iss.utils").build("sx.iss.HelpSuggestionProvider",
function(d){var c=[{type:"help",pat:/^return/i,text:"Looking for help with returns? Try this.",url:""},{type:"help",pat:/^track/i,text:"Looking for help with tracking? Try this.",url:""},{type:"help",pat:/^gift[\s*]w/i,text:"Looking for help with gift wrapping? Try this.",url:""},{type:"help",pat:/^canc/i,text:"Looking for help with order cancellation? Try this.",url:""},{type:"help",pat:/^refu[\s*]/i,text:"Looking for help with refund? Try this.",url:""},{type:"help",pat:/^passw[\s*]/i,text:"Looking for help with passwords? Try this.",
url:""},{type:"help",pat:/^log(ging\s*)?o/i,text:"Looking for help with logging out? Try this.",url:""}];return function(){this.getName=function(){return"help"};d.eventBus.listen("help-suggestionsNeeded",function(b){var g,a=[];for(g=0;g<c.length;g++)b.match(c[g].pat)&&a.push(c[g]);d.eventBus.trigger("help-suggestionsReady",{searchTerm:b,suggestions:a})},this)}});window.$Nav.when("$","sx.iss.utils").build("sx.iss.RecentSearchSuggestionProvider",function(d,c){return function(){var b=/[^\w]/;this.getName=
function(){return"recent"};c.eventBus.listen("recent-suggestionsNeeded",function(g){var a=[];if(window.sx&&window.sx.searchsuggest&&window.sx.searchsuggest.searchedText){var e=window.sx.searchsuggest.searchedText,i={},h,f,j,n,o,l,k=!g||!b.test(g)?g:d("<div></div>").text(g).html();for(n=0;n<e.length;n++)if(f=e[n].keywords,h=!f||!b.test(f)?f:d("<div></div>").html(f).text(),j=c.suggestionUtils.getPrefixPosMultiWord(f,k),!i[f]&&c.suggestionUtils.getPrefixPosMultiWord(h,g)!==-1)j===-1?(j=f,l=o=""):(o=
c.suggestionUtils.splitStringForDisplay(f,j,k.length),j=o.bprefix,l=o.prefix,o=o.suffix),a.push({type:"recent",spellCor:!1,bprefix:j,prefix:l,suffix:o,keyword:h,originalKeywords:f,deleteUrl:e[n].deleteUrl}),i[f]=1}c.eventBus.trigger("recent-suggestionsReady",{searchTerm:g,suggestions:a})},this)}});window.$Nav.when("$","sx.iss.utils","sx.iss.TemplateEngine").build("sx.iss.SuggestionDisplayProvider",function(d,c,b){return function(c,a,e){var i,h;this.getDisplay=function(a){if(i(a))return d.extend(a,
e),h(a)};i=typeof c==="string"?function(a){return a.type===c}:c;h=b(a)}});window.$Nav.when("$","sx.iss.utils").build("sx.iss.SuggestionHighlightingProvider",function(d,c){return function(){function b(a){a=a.currentTarget.id;h&&h.removeClass(h.attr("data-selected-class"));h=d("#"+a);i=parseInt(a.substr(6));h.addClass(h.attr("data-selected-class"))}function g(a){a=a.currentTarget.id;h&&h.attr("id")===a&&(h.removeClass(h.attr("data-selected-class")),h=void 0,i=-1)}var a=this,e,i=-1,h;c.eventBus.listen("suggestionsDisplayed",
function(c){var j;e=c;i=-1;h=void 0;for(c=0;c<e.suggestions.length;c++)j=d("#"+e.suggestions[c].suggestionId),j.bind("mouseover",a,b).bind("mouseout",a,g)},this).listen("upArrowPressed",function(){e&&(h&&h.removeClass(h.attr("data-selected-class")),i--,i===-1?c.eventBus.trigger("suggestionSelected",{keyword:e.searchTerm}):(i===-2&&(i=e.suggestions.length-1),h=d("#issDiv"+i),h.addClass(h.attr("data-selected-class")),c.eventBus.trigger("suggestionSelected",e.suggestions[i])))},this).listen("downArrowPressed",
function(){e&&(h&&h.removeClass(h.attr("data-selected-class")),i++,i===e.suggestions.length?(i=-1,c.eventBus.trigger("suggestionSelected",{keyword:e.searchTerm})):(h=d("#issDiv"+i),h.addClass(h.attr("data-selected-class")),c.eventBus.trigger("suggestionSelected",e.suggestions[i])))},this)}});window.$Nav.when("sx.iss.utils","sx.iss.TemplateEngine").build("sx.iss.IssDisplayProvider",function(d,c){return function(b,g,a,e,i){function h(a){d.eventBus.trigger(e.suggestionsNeeded,a)}function f(b){var c=
g.sequence(b),b=b.searchTerm,f=o++;d.timingProvider.startTimer("IssDisplayProvider",f);if(c.length===0)d.eventBus.trigger(e.noSuggestions,b);else{for(var h=a,u=0,p=0;p<c.length;p++){var r=c[p];if(r.type!=="separator")r.suggestionId="issDiv"+u,u++;var q=r,x="";x+=r.isDeepNode===!0?"s-highlight-secondary":"s-highlight-primary";q.cssClasses=x;for(var t,q=0;q<h.length;q++)if(t=h[q],t=j(t,r),t=t.getDisplay(r))break;r.display=t}h=n({suggestions:c,suggestionTitle:i.hasOwnProperty("sugText")?i.sugText:""});
d.timingProvider.stopTimer("IssDisplayProvider",f);d.eventBus.trigger(e.suggestionsReadyForDisplay,{searchTerm:b,display:h,suggestions:c})}}function j(a,b){var c=a;if(a.hasOwnProperty("provider")&&a.hasOwnProperty("partials")){for(c=0;c<a.partials.length;c++){var e=a.partials[c],d=e.provider.getDisplay(b);e.hasOwnProperty("formatter")&&(d=e.formatter.string.replace(e.formatter.toReplace,d));b[e.key]=d}c=a.provider}return c}var n=c(b),o=0;(function(){d.eventBus.listen(e.suggestionsReady,f,this);d.eventBus.listen(["parentFocused",
"searchTermChanged"],h,this)})();return{processPartials:j}}});window.$Nav.when("sx.iss.utils","sx.iss.Events").build("sx.iss.ArraySuggestionProvider",function(d,c){return function(b,g){function a(a){for(var b=[],a=a.toLowerCase(),l=0;l<i.length;l++){var k=i[l];if(k.toLowerCase().indexOf(a)!==-1&&b.length<f){var k={term:k,searchTerm:a,url:h[l]},m=d.suggestionUtils.getPrefixPos(k.term,k.searchTerm),m=d.suggestionUtils.splitStringForDisplay(k.term,m,k.searchTerm.length),k={type:j,bprefix:m.bprefix,prefix:m.prefix,
suffix:m.suffix,keyword:k.searchTerm,url:k.url,isExactMatch:k.term===k.searchTerm};b.push(k)}}a={searchTerm:a,suggestionSets:{array:b}};b=c.createEvent(e,g.suggestionsReady);d.eventBus.trigger(b,a)}var e="array",i=b[0],h=b[1],f=10,j="array";(function(){var b=c.createEvent(e,g.suggestionsNeeded);d.eventBus.listen(b,a,this)})();return{name:e}}});window.$Nav.when("$","sx.iss.utils","sx.iss.TimingEvents","sx.iss.TemplateEngine","NavDomApi","sx.iss.SuggestionTypes","sx.iss.ReftagBuilder").build("sx.iss.DesktopSearchBoxEventHandler",
function(d,c,b,g,a,e,i){var h=a.getSearchApi();return function(f){function j(){s=!0;p||(p=!0)}function n(){u=!0}function o(){a.activateSearchBox()}function l(){a.deactivateSearchBox()}c.eventBus.listen(f.selectionChange,function(e){k===void 0&&(k=a.getAliasFromDropdown());if(e.isScrollIntoSearchBox===!0)e=e.searchTerm,a.getIssPrefixElem().remove(),m.val(e),e=a.getOption(),e=e.length>0?e.val():"search-alias="+k,a.getAliasDropdown().val(e).trigger("change");else{var f=c.timingProvider.getTimingWithDisplayLatency(b.latency.group,
b.latency.events.timeToDisplay),f=a.getKeyword()+","+a.getOriginalAlias()+","+f,h=a.getIssPrefixElem();h.length>0?h.attr("value",f):(f=d('<input type="hidden"/>').attr("id","issprefix").attr("name","sprefix").attr("value",f),a.getForm().append(f));var e=e.suggestion,i=e.attr("data-alias"),h=a.getOption(i),f=a.getAliasDropdown(),i="search-alias="+i;h.length===0?(h=e.data("store"),h!==void 0&&h!==""&&f.append(g("s-option",{value:i,store:h}))):i=h.val();f.val(i).trigger("change");a.setKeyword(e.attr("data-keyword"))}});
c.eventBus.listen(f.hideDropdown,function(b){s===!0&&u===!0&&(b.keyCode===27||b.keyCode===13)?(s=u=!1,c.eventBus.triggerThrottledEvent(f.suggestionsNeeded,a.getKeyword())):(a.hideDropdown(),a.getIssPrefixElem().remove(),k=void 0)});c.eventBus.listen(f.suggestionClicked,function(b){c.eventBus.trigger(f.updateSearchBox,b);var d={suggestion:b,searchTerm:a.getKeyword()};c.eventBus.trigger(f.selectionChange,d);a.hideDropdown();b.attr("data-type")===e.a9Corpus.name?(b=b.attr("data-url"),window.location=
b.replace(e.a9Corpus.reftagTemplate,(new i).buildFull(d,p))):a.submitForm()});c.eventBus.listen(f.noSuggestions,function(){a.hideDropdown()});c.eventBus.listen(f.suggestionsNeeded,function(){k=a.getAliasFromDropdown()});h===void 0&&(c.eventBus.listen(f.searchBoxFocusIn,o),c.eventBus.listen(f.searchBoxFocusOut,l));h!==void 0?(h.on("compositionstart",j),h.on("compositionend",n)):d("#navbar").delegate("#twotabsearchtextbox","compositionstart",j).delegate("#twotabsearchtextbox","compositionend",n);var k,
m=a.getSearchBox(),s=!1,u=!1,p=!1;return{getWasCompositionUsed:function(){return p}}}});window.$Nav.when("sx.iss.utils").build("sx.iss.A9SearchSuggestionEventHandler",function(d){return function(){var c;this.getDelegateReqs=function(){return{selectors:".a9_suggestion,.suggestion_with_query_builder",events:"click"}};this.handleEvent=function(b){var g=b.target||b.srcElement,b=parseInt(b.currentTarget.id.substr(6),10);g.className&&g.className.indexOf("suggest_builder")!=-1?d.eventBus.trigger("updateSearchTerm",
c.suggestions[b].keyword):d.eventBus.trigger("suggestionClicked",c.suggestions[b])};d.eventBus.listen("suggestionsDisplayed",function(b){c=b},this)}});window.$Nav.when("sx.iss.utils").build("sx.iss.RecentSearchSuggestionEventHandler",function(d){return function(){function c(a){var b,c,g,f;b=location.protocol+"//"+location.host+a.deleteUrl;c=window.sx.searchsuggest.searchedText;for(g=0;g<c.length;g++)if(c[g].keywords===a.originalKeywords){f=g;break}f!==-1&&c.splice(f,1);d.eventBus.trigger("focusOnParent");
var j;window.XMLHttpRequest?j=new XMLHttpRequest:window.ActiveXObject&&(j=new ActiveXObject("Microsoft.XMLHTTP"));if(j&&b)try{j.open("GET",b,!0),j.send(null)}catch(n){}}var b=this,g;this.getDelegateReqs=function(){return{selectors:".recent_search_suggestion",events:"click"}};this.handleEvent=function(a){var e=a.target||a.srcElement,a=parseInt(a.currentTarget.id.substr(6),10);e.className&&e.className.indexOf("iss_sh_delete")!=-1?c.call(b,g.suggestions[a]):d.eventBus.trigger("suggestionClicked",g.suggestions[a])};
d.eventBus.listen("suggestionsDisplayed",function(a){g=a},this)}});window.$Nav.when("$","sx.iss.utils","sx.iss.DomUtils","sx.iss.TimingEvents","sx.iss.TemplateEngine","sx.iss.DebugUtils").build("sx.iss.SearchBoxEventHandler",function(d,c,b,g,a,e){var i=[37,38,39,40,91,92,93,192];return function(a,f,g){function n(a){c.eventBus.trigger(g.keydown);var f=a.keyCode,h=f===40,i=f===38,k;if(p.find("#suggestions-template").is(":visible")){if(h||i){q===void 0&&(q=b.getKeyword(r));var m=p.find(".s-suggestion"),
l=m.index(d(".s-selected"));(i=l===0&&i||l+1===m.length&&h)?p.find(".s-suggestion").removeClass("s-selected"):(e.logDebug("highlighting suggestion"),k=p.find(".s-suggestion"),m=k.index(s()),l=k.length,h?(h=-1,m===-1||m===l-1?h=0:m<l&&(h=m+1)):(h=-1,m<1?h=l-1:m<=l&&(h=m-1)),k.eq(m).removeClass("s-selected"),h=k.eq(h),h.addClass("s-selected"),k=h);c.eventBus.trigger(g.selectionChange,{suggestion:k,isScrollIntoSearchBox:i,searchTerm:q});r.val()!==""&&a.preventDefault()}f===13&&(f=s(),f.length>0&&(c.eventBus.trigger(g.suggestionClicked,
f),a.preventDefault()))}}function o(a){a=a.keyCode;a===13?m(a):a===27?m(a):(q=b.getKeyword(r),q!==x&&i.indexOf(a)===-1&&(q===void 0||q===""?(m(),x=""):(c.eventBus.triggerThrottledEvent(g.suggestionsNeeded,q),x=q)))}function l(){setTimeout(function(){return function(){m();c.eventBus.trigger(g.searchBoxFocusOut)}}(),300)}function k(){c.eventBus.trigger(g.searchBoxFocusIn)}function m(a){q=void 0;c.eventBus.trigger(g.hideDropdown,{keyCode:a})}function s(){return p.find(".s-suggestion.s-selected")}var u,
p,r,q,x;(function(){if(f!==void 0){u=f.$form;p=f.$dropdown;r=f.$searchbox;var a="#"+r.attr("id");u.delegate(a,"focusin",k).delegate(a,"focusout",l).delegate(a,"keydown",n).delegate(a,"keyup",o);x=r.val()}})()}});window.$Nav.when("$","sx.iss.utils","NavDomApi","sx.iss.DomUtils","sx.iss.DebugUtils").build("sx.iss.SuggestionEventHandler",function(d,c,b,g,a){return function(b,i){i.delegate(".s-suggestion","click",function(g){var f=d(this);a.logDebug("Suggestion clicked",f);c.eventBus.trigger(b.suggestionClicked,
f);g.preventDefault()}).delegate(".s-suggestion","mouseover",function(a){g.hoverOverEl(d(a.currentTarget))}).delegate(".s-suggestion","mouseout",function(a){g.hoverOutEl(d(a.currentTarget))})}});window.$Nav.when("$","sx.iss.utils","sx.iss.DebugUtils","sx.iss.DomUtils").build("sx.iss.CustomSearchBoxEventHandler",function(d,c,b,g){return function(a,e,i){function h(a){n.hide();typeof i.manualOverride==="function"&&(a=i.manualOverride(a),a!==null&&a.length>0&&f(a));d(i.submitId).removeAttr("disabled")}
function f(a){j.find(g.hiddenInputClass).remove();a=g.getFormParams(a);b.logDebug("Updating form with params.",a);j.attr("action",a.uri);for(var c="",a=a.formParams,e=0;e<a.length;e++){var d=a[e],f=decodeURIComponent(d.value);c+='<input type="hidden" class="'+g.hiddenInputValue+'" name="'+d.name+'" value="'+f+'"/>'}j.append(c)}var j,n;j=a.$form;n=a.$dropdown;c.eventBus.listen(e.suggestionClicked,function(a){b.logDebug("Suggestion clicked",a);f(a.data("url"));j.submit()});c.eventBus.listen(e.noSuggestions,
function(a){h(a)});c.eventBus.listen(e.suggestionsReadyForDisplay,function(a){a.suggestions.length===2&&a.suggestions[1].type==="separator"&&a.suggestions[0].isExactMatch===!0?(a=n.find(g.suggestionClass).eq(0),f(a.data("url"))):a.searchTerm.length>=4?h(a.searchTerm):d(i.submitId).attr("disabled","disabled")});c.eventBus.listen(e.hideDropdown,function(){n.hide()})}});window.$Nav.when("sx.iss.utils","sx.iss.Events","sx.iss.TimingEvents","sx.iss.MetricsLogger").build("sx.iss.SuggestionAggregator",function(d,
c,b,g){return function(a,e){function i(h){d.timingProvider.startTimer(b.latency.group,b.latency.events.timeToDisplay);g.startEndToEndLogging();if(!f[h]){f[h]={remainingProviders:e.length,searchTerm:h,suggestionSets:{}};for(var i=0;i<e.length;i++){var o=c.createEvent(e[i],a.suggestionsNeeded);d.eventBus.trigger(o,h)}}}function h(b){var c=f[b.searchTerm],b=b.suggestionSets,e;for(e in b)b.hasOwnProperty(e)&&(c.suggestionSets[e]=b[e]);--c.remainingProviders||(delete f[c.searchTerm],d.eventBus.trigger(a.suggestionsReady,
c))}var f={};(function(){for(var b=0;b<e.length;b++){var f=c.createEvent(e[b],a.suggestionsReady);d.eventBus.listen(f,h,this)}d.eventBus.listen(a.suggestionsNeeded,i,this)})()}});window.$Nav.when("$","sx.iss.utils","sx.iss.SuggestionTypes").build("sx.iss.SuggestionSequencer",function(d,c,b){return function(d){var a=[b.department.name,b.a9Corpus.name,b.a9Xcat.name,b.a9.name,"array"],e={type:"separator"};this.sequence=function(b){for(var c=b.suggestionSets,b=[],f=0,j=this.isDeepNode(d),n=0;n<a.length;n++){var o=
c[a[n]];if(!(typeof o==="undefined"||o.length===0)){for(var l=0;l<o.length&&f<10;l++){var k=o[l];k.dispIdx=b.length;b.push(k);f++}f>0&&!j&&b.push(e)}}j&&(b=this.sequenceDeepNodeResults(b));c=b.length;c>0&&b[c-1].type==="separator"&&b.splice(-1,1);return b};this.isDeepNode=function(a){var b,e;a.deepNodeISS&&(b=c.suggestionUtils.getDeepNodeAlias(a.deepNodeISS),e=c.suggestionUtils.getDeepNodeCategoryName(b,a.deepNodeISS));return b!==void 0&&e!==void 0};this.sequenceDeepNodeResults=function(a){for(var c,
e,d=[],g=0;g<a.length;g++)e=a[g],c===b.a9Xcat.name&&e.type===b.a9.name?d.unshift(e):d.push(e),c=e.type;return d}}});window.$Nav.when("$","sx.iss.utils","sx.iss.Events","NavDomApi").build("sx.iss.MetricsLogger",function(d,c,b,g){function a(){var a=g.isSearchBoxFocused()?j:f;ue.tag(a)}function e(){uet(n,h,k);uet(o,h,k);uex(l,h,k)}function i(){return typeof uet==="function"&&typeof uex==="function"}var h="iss-init-pc",f="iss-on-time",j="iss-late",n="cf",o="be",l="ld",k={wb:1};i()&&(c.eventBus.listen(b.globals.initializeNavSearchBox,
a),c.eventBus.listen(b.globals.issLoaded,e));return{startEndToEndLogging:function(){i()&&uet("bb","iss-end-to-end-a9",k)},stopEndToEndLogging:function(){i()&&(uet(n,"iss-end-to-end-a9",k),uet(o,"iss-end-to-end-a9",k),uex(l,"iss-end-to-end-a9",k))}}});window.$Nav.when("$","sx.iss.utils","sx.iss.TimingEvents","sx.iss.SuggestionTypes","sx.iss.SearchBoxEventHandler","sx.iss.A9SuggestionProvider","sx.iss.DepartmentSuggestionProvider","sx.iss.SuggestionAggregator","sx.iss.SuggestionDisplayProvider","sx.iss.SuggestionSequencer",
"sx.iss.IssDisplayProvider","sx.iss.TemplateInstaller","sx.iss.SuggestionEventHandler","sx.iss.DesktopSearchBoxEventHandler","NavDomApi","sx.iss.Events","sx.iss.Reftag","sx.iss.Weblab","sx.iss.DebugUtils","sx.iss.MetricsLogger").build("sx.iss.IssParentCoordinator",function(d,c,b,g,a,e,i,h,f,j,n,o,l,k,m,s,u,p,r,q){return function(d){var t,w,v=!1;w={$form:m.getForm(),$dropdown:m.getDropdown(),$searchbox:m.getSearchBox()};t=s.createInstance();m.getForm().data("originalSearchTerm",m.getKeyword());m.getForm().data("originalAlias",
m.getAliasFromDropdown());(function(){new a(d,w,t);o.init();var b=[(new e("desktop",d,t)).getName()],q=[new f(g.a9.name,g.a9.templateId),new f(g.a9Corpus.name,g.a9Corpus.templateId),new f("separator","s-separator")],r={provider:new f(g.a9Xcat.name,g.a9Xcat.templateId),partials:[{key:"storeHtml",provider:new f(g.a9Xcat.name,"s-storeText"),formatter:{string:d.deptText,toReplace:"{department}"}}]};q.push(r);d.hasOwnProperty("isDigitalFeaturesEnabled")&&d.isDigitalFeaturesEnabled===1&&(q.push(new f(g.department.name,
g.department.templateId)),r=new i(d,t),b.push(r.getName()));new n("suggestions-template",new j(d),q,t,d);new h(t,b);c.eventBus.trigger(s.globals.initializeNavSearchBox);b=new k(t,d);new u(t,d,{shouldAddImeTag:b.getWasCompositionUsed});new l(t,m.getDropdown());new p(d,t)})();c.eventBus.listen(t.suggestionsReadyForDisplay,function(a){v&&(w.$searchbox.val().length===0?r.logDebug('Search term is empty, abort rendering for the search term "'+a.searchTerm+'"'):(m.showDropdown(a.display),c.timingProvider.stopTimer(b.latency.group,
b.latency.events.timeToDisplay),q.stopEndToEndLogging(),c.eventBus.trigger(t.suggestionsRendered,a),c.eventBus.trigger(s.globals.suggestionsRendered,a)))});c.eventBus.listen(t.hideDropdown,function(){v=!1});c.eventBus.listen(t.suggestionsNeeded,function(){v=!0})}});window.$Nav.when("$","sx.iss.utils","sx.iss.SearchBoxEventHandler","sx.iss.SuggestionAggregator","sx.iss.SuggestionDisplayProvider","sx.iss.SuggestionSequencer","sx.iss.IssDisplayProvider","sx.iss.TemplateInstaller","sx.iss.SuggestionEventHandler",
"sx.iss.Events","sx.iss.DomUtils","sx.iss.ArraySuggestionProvider","sx.iss.CustomSearchBoxEventHandler").build("sx.iss.CustomParentCoordinator",function(d,c,b,g,a,e,i,h,f,j,n,o,l){return function(k){var m,s;(function(){h.init();m=j.createInstance();var c=k.searchboxId,p=d(k.formId),r=d('<div id="search-dropdown-custom" class="search-dropdown"></div>');p.after(r);s={$form:p,$dropdown:r,$searchbox:d(c)};s.$dropdown.css({width:s.$searchbox.outerWidth()});new b(k,s,m);new f(m,s.$dropdown);new l(s,m,k);
k.hasOwnProperty("src")&&n.isArray(k.src)&&(c=new o(k.src,m),new g(m,[c.name]));c=[new a("array","s-minimal")];new i("suggestions-template",new e(k),c,m,k)})();c.eventBus.listen(m.suggestionsReadyForDisplay,function(a){s.$dropdown.html(a.display);s.$dropdown.show();c.eventBus.trigger(m.suggestionsRendered,a)});return{dropdownId:"search-dropdown-custom"}}});window.$Nav.when("$","sx.iss.utils","sx.iss.Events","sx.iss.A9SuggestionProvider","sx.iss.DepartmentSuggestionProvider","sx.iss.A9SearchSuggestionEventHandler",
"sx.iss.HelpSuggestionProvider","sx.iss.RecentSearchSuggestionProvider","sx.iss.RecentSearchSuggestionEventHandler","sx.iss.SuggestionHighlightingProvider","sx.iss.SuggestionAggregator","sx.iss.SuggestionSequencer","sx.iss.SuggestionDisplayProvider","sx.iss.IssDisplayProvider","sx.iss.IssParentCoordinator","sx.iss.PublicApi","sx.iss.MetricsLogger","sx.iss.CustomParentCoordinator").build("sx.iss",function(d,c,b,g,a,e,i,h,f,j,n,o,l,k,m,s,u,p){g={A9SuggestionProvider:g,DepartmentSuggestionProvider:a,
A9SearchSuggestionEventHandler:e,HelpSuggestionProvider:i,RecentSearchSuggestionProvider:h,RecentSearchSuggestionEventHandler:f,SuggestionHighlightingProvider:j,SuggestionAggregator:n,SuggestionSequencer:o,SuggestionDisplayProvider:l,IssDisplayProvider:k,IssParentCoordinator:m,CustomParentCoordinator:p,IssParentCoordinatorMobile:m,SuggestionSequencerMobile:o,isNewIss:!0};d.extend(g,g,s);c.eventBus.trigger(b.globals.issLoaded);return g});window.$Nav.when("sx.iss").run(function(d){window.$Nav.publish("sx.iss",
d);window.$Nav.publish("search-js-autocomplete",d)})})})(function(){var C=window.AmazonUIPageJS||P,d=C.attributeErrors;return d?d("RetailSearchAutocompleteAssets"):C}());
;/* RetailSearchClientSideLoggingAuiAssets */
(function(d){d.execute(function(){if(!window.$SearchJS&&window.$Nav)window.$SearchJS=$Nav.make("sx");window.$SearchJS&&($SearchJS.importEvent("jQuery",{as:"$",global:"jQuery"}),$SearchJS.importEvent("jQuery",{global:"jQuery"}),$SearchJS.when("jQuery").run("searchCSL-lib",function(c){c.searchCSL=c.searchCSL||new function(){var b=this,g=[],e=[],d,i,j,f,h=200,k;b.init=function(a,l,c){a&&l&&!d&&(d=a,b.updateRid(l),c&&(h=c))};b.updateRid=function(a){a&&i!=a&&(b.tx(),i=a,j={})};b.addWlt=function(a){if(a){if(a.call&&
(a=a(),!a))return;j[a]||(g.push(a),j[a]=1,b.scheduleTx())}};b.addAmabotPrerendered=function(a){a&&a.rid&&a.selections&&a.selections.length&&(e.push(a),b.scheduleTx())};b.scheduleTx=function(){if(h==0)b.tx();else{if(!k){var a=window.onbeforeunload;window.onbeforeunload=function(c){f&&(window.clearInterval(f),f=void 0);b.tx();k=!1;return a&&a.call?a(c):void 0};k=!0}!f&&h>0&&(f=window.setTimeout(function(){f=void 0;b.tx()},h))}};b.tx=function(){if(g.length||e.length){var a="/mn/search/csl?";g.length&&
(a+="rrid="+i+"&cpt="+d+"&ctw="+g.join("|"),g=[]);if(e.length){var b="";c.each(e,function(a,d){b+=d.rid+":";c.each(d.selections,function(a,c){c&&(b+=c+(a!=d.selections.length-1?",":""))});b+=a!=e.length-1?".":""});e=[];b&&(a+=a.charAt(a.length-1)=="?"?"":"&",a+="amabotSelections="+b)}(new Image).src=a}}};$SearchJS.publish("search-csl",c.searchCSL)}))})})(function(){var d=window.AmazonUIPageJS||P,c=d.attributeErrors;return c?c("RetailSearchClientSideLoggingAuiAssets"):d}());
;/* P13NSharedSitewideJS */
(function(c){c.execute(function(){(function(){c.register("p13n-sc-math",function(){return Math});c.register("p13n-sc-document",function(){return document});c.register("p13n-sc-window",function(){return window});c.register("p13n-sc-undefined",function(){});var b=function(){return window.P&&window.P.AUI_BUILD_DATE};b()?(c.when("jQuery").register("p13n-sc-jQuery",function(b){return b}),c.when("ready").register("p13n-sc-ready",function(){})):window.amznJQ&&(window.amznJQ.available("jQuery",function(){c.register("p13n-sc-jQuery",
function(){return window.amznJQ.jQuery})}),window.amznJQ.onReady("jQuery",function(){c.register("p13n-sc-ready",function(){})}),window.amznJQ.available("amazonShoveler",function(){c.register("p13n-sc-amznJQ-shoveler",function(){})}));c.when("p13n-sc-window").register("p13n-sc-util",function(f){var g=f.ueLogError;typeof g!=="function"&&(g=function(b,f){if(f&&f.message)throw Error(f.message);if(b&&b.message)throw Error(b.message);});var c=function(b,f){g({logLevel:b,attribution:"P13NSharedSitewideJS",
message:"[p13n-sc] "+f})};return{constants:{DATA_ATTR_P13N_FEATURE_NAME:"p13nFeatureName"},count:f.ue&&f.ue.count||function(){},isAUI:b,log:{warn:function(b){c("WARN",b)},error:function(b){c("ERROR",b)}}}})})();c.when("p13n-sc-jQuery","p13n-sc-window","p13n-sc-undefined").register("p13n-sc-heartbeat",function(b,f,c){var i=f.clearInterval,e={},k,l,a=function(){if(!k){var a=f.setInterval(function(){var b=a,f=(new Date).getTime();b!==k?i(b):((!l||f-l>200)&&j(),l=(new Date).getTime())},200);k=a}},j=function(){b.each(e,
function(a,b){b.call(f)})};return{subscribe:function(b,d){e[b]||(e[b]=d,a())},unsubscribe:function(a){e[a]&&delete e[a];var a=!0,b;for(b in e)e.hasOwnProperty(b)&&(a=!1);a&&(i(k),k=c)}}});c.when("p13n-sc-jQuery","p13n-sc-heartbeat").register("p13n-sc-call-on-visible",function(b,f){var c=[],i=b(window),e=function(){for(var b=i.scrollTop()+i.height(),e=i.scrollLeft()+i.width(),a=c.length-1;a>=0;a--){var j=c[a],h=j.callback,d=j.$element,o=j.distanceY,j=j.distanceX;if(d.parents("body").size()===0)c.splice(a,
1);else if(!d.is(":hidden")){var n=d.offset();b-o>n.top&&e-j>n.left&&(h.call(null,d[0]),c.splice(a,1))}}c.length===0&&f.unsubscribe("p13n-sc-call-on-visible")};return{register:function(k,i,a){var j=a&&typeof a.distance!=="undefined"?a.distance:0,h=a&&typeof a.distanceY!=="undefined"?a.distanceY:j,d=a&&typeof a.distanceX!=="undefined"?a.distanceX:0;b(k).each(function(){c.push({$element:b(this),callback:i,distanceY:h,distanceX:d})});f.subscribe("p13n-sc-call-on-visible",e);e()}}});c.when("A","jQuery",
"p13n-sc-call-on-visible","p13n-sc-util","p13n-sc-math").register("p13n-sc-view-trigger",function(b,f,g,i,e){var k=function(a){var c=f(a),a=c.attr("data-params"),h=c.attr("data-url");if(a&&h){var a=b.parseJSON(a),d=c.offset(),c=[d.top,d.left,c.height(),f(window).width()];a.elementRect=c.join(",");var g=0,k={cache:!0,crossDomain:!1,data:f.param(a,!1),error:function(a){a=a.status||0;g>=3||a>=400&&a<500||setTimeout(i,200*e.pow(2,g))},global:!1,url:h},i=function(){g+=1;f.ajax(k)};i()}},l=function(a){var e=
f(a);if(e.size()===1){var h=e.attr("data-params"),h=h?b.parseJSON(h):{};if(!(h.allowEmpty!==!0&&e.text().trim().length===0)){var d=e.height();if(!(h.allowEmpty!==!0&&d<5)){d=0;if(typeof h.distance==="number")d=h.distance;e.attr("data-p13n-sc-vt-initialized")||(e.attr("data-p13n-sc-vt-initialized",!0),g.register(a,function(){k(a)},{distance:d}))}}}},i=function(){b.each(f(".p13n-sc-vt:not([data-p13n-sc-vt-initialized])"),function(a){l(a)})};c.execute(i);c.when("afterReady").execute("p13n-sc-view-trigger:init",
i);return{initializeElement:l}});c.when("p13n-sc-jQuery","p13n-sc-util","p13n-sc-window","p13n-sc-document","p13n-sc-ready").register("p13n-sc-logger",function(b,f,c,i){function e(a){return a.join("")}function k(a,b){var d=a.attr(b),h={};d!==void 0&&d!==null&&(h=typeof c.JSON!=="undefined"?JSON.parse(d):eval("("+d+")"));return h}function l(a,d){for(var h=[a.widget,":"],f=0;f<a.asins.length;f++){var c=a.asins[f];h.push(c.asin,"@");b.each(c,function(a,b){a!=="asin"&&h.push(a,"=",b,"|")});h.splice(h.length-
1,1);h.push(",")}a.asins.length>0&&h.splice(h.length-1,1);d&&(h.push(":","action=",a.action),b.each(a.meta,function(a,b){h.push(",",a,"=",b)}));return e(h)}function a(a,d){var h=k(b(d),"data-p13n-asin-metadata");if(h&&h.asin){var f=h.asin,e=k(b(a),"data-p13n-asin-metadata");e&&b.extend(!0,h,e[f]);return h}}function j(a,h){var j=new Image;f.count("p13n:logger:attempt",1);j.onerror=function(){d++;f.count("p13n:logger:error",1)};j.src=e(["https:"===i.location.protocol?"https://":"http://",c.ue_furl||
"fls-na.amazon.com","/1/","p13n-shared-components","/1/OP/p13n/",h,e(["?",b.param(k(b(a.featureElement),"data-p13n-global"))])])}function h(){return d>3?(o||(f.log.warn("impression image load failed too many times, no longer logging impressions"),f.count("p13n:logger:abort",1),o=!0),!0):!1}var d=0,o=!1,n={},p={},q={logAction:function(d){if(!h())if("featureElement"in d)if("action"in d){var c=b(d.featureElement);d.asins=b.map(b(d.featureElement).find(".p13n-asin").filter(":visible"),function(b){return a(c,
b)});d.meta=d.meta||{};var g=k(c,"data-p13n-feature-metadata");b.extend(!0,d.meta,g);d.widget=c.attr("data-p13n-feature-name");d.widget in n||(n[d.widget]={});for(var i=g=0;i<d.asins.length;i++)d.asins[i].asin in n[d.widget]||(n[d.widget][d.asins[i].asin]=!0,g++);d.logOnlyOnNew&&g===0||(g=e(["action/",e([d.widget,"_:",d.action,"@v=",d.eventtime||0,",impressed@v=",g]),"/",l(d,!0)]),d.replicateAsinImpressions&&(i=e(["asin/",l(d,!1)]),g=e(["batch/",g,"$",i])),j(d,g))}else f.log.warn("action missing in eventData for logAction");
else f.log.warn("featureElement missing in eventData for logAction")},logAsyncAction:function(a){var d=(new Date).getTime(),h=typeof a.initialDelay==="number"?a.initialDelay:400,f=typeof a.timeout==="number"?a.timeout:5E3,e=b(a.featureElement);a.widget=e.attr("data-p13n-feature-name");a.widget in p&&c.clearTimeout(p[a.widget]);var j=function(){var b=a.isEventComplete(),h=(new Date).getTime();if(h-d<f&&!b)p[a.widget]=c.setTimeout(j,150);else{if(!b){if(!("meta"in a))a.meta={};a.meta.err="notfinished"}a.eventtime=
h-d;delete p[a.widget];q.logAction(a)}};p[a.widget]=c.setTimeout(j,h)},eventPending:function(a){return b(a).attr("data-p13n-feature-name")in p},impressAsin:function(d){if(!h())if("featureElement"in d)if("faceoutElement"in d){var c=b(d.faceoutElement),g=b(d.featureElement);d.widget=g.attr("data-p13n-feature-name");d.asins=[a(g,c)];c=e(["asin/",l(d,!1)]);j(d,c)}else f.log.warn("faceoutElement missing in eventData for logAction");else f.log.warn("featureElement missing in eventData for logAction")}};
return q});c.when("jQuery","A","p13n-sc-call-on-visible","p13n-sc-logger","ready").register("p13n-sc-faceout-logger",function(b,f,c,i){var e=function(f,e){var a=b(f),j=b(e);a.length===1&&!a.attr("data-p13n-sc-fl-initialized")&&(a.attr("data-p13n-sc-fl-initialized",!0),c.register(a,function(){i.impressAsin({featureElement:j,faceoutElement:a})}))};f.on("p13n:faceoutsloaded",function(f){b(f).find(".p13n-asin:not([data-p13n-sc-fl-initialized])").each(function(b,a){e(a,f)})})});c.when("A","jQuery").register("p13n-sc-lazy-image-loader",
function(b,f){return{loadImages:function(c){b.executeDeferred();c.find(".p13n-sc-lazy-loaded-img").each(function(c,e){var g=f(e),l=g.find(".a-dynamic-image");l.load(function(){g.removeClass("p13n-sc-lazy-loaded-img")});b.loadDynamicImage(l)})}}});c.when("p13n-sc-jQuery","p13n-sc-util","p13n-sc-math","p13n-sc-line-truncator-settings").register("p13n-sc-line-truncator",function(b,f,c,i){function e(a){this.$element=a;this.$experimentElement=b("<div>").addClass("p13n-sc-offscreen-truncate");this.maxRows=
a.data("rows");this.lineHeight=i.lineHeight;this.maxRows||f.log.error("Truncation element missing necessary line number data")}var k=/(?=[ \-\/])/,l=/[^\/\-\[\]():\s]/;e.prototype.truncate=function(){var a=this.$element.html();this.$element.append(this.$experimentElement);if(!this.checkLineFit(a)){var b=this.truncateByToken(a);b?(this.$element.html(b),this.$element.attr({title:a})):f.log.error("Unable to successfully truncate line "+a)}this.$experimentElement.remove()};e.prototype.checkLineFit=function(a){this.$experimentElement.html(a);
a=this.$experimentElement.get(0).clientHeight/this.lineHeight;return c.round(a)<=this.maxRows};e.prototype.truncateByToken=function(a){for(var a=a.split(this.getTokenSeparatorRegex()),b=1,h=a.length,d,f,e=0;b!==h;)if(d=c.floor((h+b)/2),f=a.slice(0,d).join("")+"&hellip;",this.checkLineFit(f)){if(h-d<=1){for(e=d;e>0&&!l.test(a[e-1]);)e--;break}b=d}else h=d;return e===0?void 0:a.slice(0,e).join("")+"&hellip;"};e.prototype.getTokenSeparatorRegex=function(){return this.$element.data("truncateByCharacter")?
"":k};return{truncateLines:function(a){a.find(".p13n-sc-truncate").each(function(){var a=new e(b(this));a&&a.truncate()})}}});c.register("p13n-sc-line-truncator-settings",function(){return{lineHeight:19}});c.when("A","jQuery","a-carousel-framework","p13n-sc-call-on-visible","p13n-sc-logger","p13n-sc-util","ready").execute("p13n-sc-carousel-logger",function(b,f,c,i,e,k){function l(a,b){var c=a.getAttr("pageNumber"),g=a.dom.$container;g.data("p13nPreviousPage",c);e.logAsyncAction(f.extend(!0,{},{featureElement:g,
isEventComplete:function(){return g.find(".a-carousel-card-empty").size()===0&&!a.getAttr("animating")},meta:{page:c},replicateAsinImpressions:!0},b))}function a(a){j(a)&&i.register(a.dom.$container,function(){l(a,{action:"view"})})}var j=function(a){return typeof a==="undefined"?!1:a.dom.$container.data(k.constants.DATA_ATTR_P13N_FEATURE_NAME)?!0:!1};b.each(c.getAllCarousels(),function(b){b.dom.$container.hasClass("a-carousel-initialized")&&a(b)});b.on("a:carousel:init",function(b){a(b.carousel)});
f(document).delegate(".a-carousel-container[data-p13n-feature-name] .a-carousel-goto-nextpage","click",function(a){a=c.getCarousel(a.target);l(a,{action:"next_page"})});f(document).delegate(".a-carousel-container[data-p13n-feature-name] .a-carousel-goto-prevpage","click",function(a){a=c.getCarousel(a.target);l(a,{action:"prev_page"})});f(document).delegate(".a-carousel-container[data-p13n-feature-name] .a-carousel-restart","click",function(a){a=c.getCarousel(a.target);l(a,{action:"start_over",meta:{op:a.dom.$container.data("p13nPreviousPage")}})});
b.on("a:carousel:change:pageSize",function(a){a=a.carousel;j(a)&&a.dom.$container.hasClass("a-carousel-initialized")&&l(a,{action:"resize",logOnlyOnNew:!0})})});c.when("p13n-sc-jQuery","p13n-sc-window","p13n-sc-document","p13n-sc-call-on-visible","p13n-sc-logger","p13n-sc-util","p13n-sc-amznJQ-shoveler").register("p13n-sc-non-aui-carousel",function(b,f,g,i,e,k){var l=function(a){k.count("p13n-sc-non-aui-carousel:init",1);var d=a.attr("data-widgetname"),c=b("#"+d+"Data");if(c.length!==1)return!1;if(a.attr("data-p13n-sc-carousel-initialized"))return!1;
else a.attr("data-p13n-sc-carousel-initialized",!0);var g=c.text().split(","),j=a.find(".shoveler-content > ul"),i="input#"+d+"ShvlState",m=function(){},l=200,u=!1,w=function(){var d=l;a.find(".p13nimp, .p13n-asin").each(function(){var a=b(this).outerHeight(!0);a>d&&(d=a)});d>l&&(l=d,j.animate({height:d},200,"linear"));u||x()},x=function(){var b=l/2;a.find("a.next-button, a.back-button").css("top",b);u=!0},r=a.find(".shoveler").shoveler(function(a,d){var e="",e=typeof f.JSON!=="undefined"?JSON.parse(c.attr("data-ajax")):
eval("("+c.attr("data-ajax")+")");e.asins=g.slice(a,a+d).join(",");e.count=d;e.offset=a;e=b.param(e);return c.attr("data-url")+"?"+e},g.length,{cellTransformer:function(a){return a===null?"":a},cellChangeSpeedInMs:30,preloadNextPage:!0,prevButtonSelector:"a.back-button",nextButtonSelector:"a.next-button",startOverSelector:"span.start-over",startOverLinkSelector:"a",horizPadding:14,state:{ready:function(){return b(i).val().length>0},get:function(){return parseInt(b(i).val(),10)},set:function(a){b(i).val(a)}},
onUpdateUIHandler:function(){w();m()}}),v=0,y=function(){var a=b(f).width();v!==a&&(r.updateUI(),v=a)},t=null;a.resize(function(){t&&f.clearTimeout(t);t=f.setTimeout(y,100)});var s=function(d){e.logAsyncAction(b.extend(!0,{},{featureElement:a,isEventComplete:function(){return a.find("li.shoveler-cell.shoveler-progress").size()===0}},d))};s({action:"view",page:r.getCurrentPage()+1});a.find(".back-button").click(function(){s({action:"shovel_left",page:r.getCurrentPage()+1})});a.find(".next-button").click(function(){s({action:"shovel_right",
page:r.getCurrentPage()+1})});a.find(".start-over-link").mousedown(function(){s({action:"start_over",page:1,meta:{op:r.getCurrentPage()+1}})});m=function(){e.eventPending(a)||s({action:"resize",page:r.getCurrentPage()+1,logOnlyOnNew:!0,initialDelay:2E3})}},a=function(a){var d={distanceY:-250,distanceX:0};b(a).find(".p13n-sc-nonAUI-carousel").andSelf().filter(".p13n-sc-nonAUI-carousel").each(function(a,e){i.register(e,function(){l(b(e))},d)})},j=function(){a(g)};j();c.when("p13n-sc-ready").execute("p13n-sc-non-aui-carousel:readyInit",
j);return{init:a}});c.when("p13n-sc-jQuery","p13n-sc-util").execute("p13n-sc-carousel-initialization-setup",function(b,f){f.isAUI()?c.when("a-carousel-framework").register("p13n-sc-carousel-init",function(b){return{init:function(){b.createAll()}}}):c.when("p13n-sc-non-aui-carousel").register("p13n-sc-carousel-init",function(b){return{init:function(c){b.init(c)}}})})})})(function(){var c=window.AmazonUIPageJS||P,b=c.attributeErrors;return b?b("P13NSharedSitewideJS"):c}());
